### ISSUE TITLE
Strange line in .gitignore file

### ISSUE THREAD

**Issue by georgeyjm** [chenyx512/Jiezi#3]
In the `.gitignore` file, there is a strange file that is ignored in [line 4](https://github.com/chenyx512/Jiezi/blob/master/.gitignore#L4):

```jiezi/jiezi/__init__.py```

I wonder why this file should be ignored. Was it a mistake?

**Comment by chenyx512** [comment]
If MySQL is used, Mac users may need to import pymysql as MySQLdb, which causes trouble in windows and Linux. This ignore of init file shouldn’t cause any trouble because the file on git is blank as it should be, and it should never be changed in the future.

However, there may be better ways to resolve the issue, so this issue will remain open until the project is reconstructed.

**Comment by chenyx512** [comment]
At this point, we have cleaned up the .gitignore file as well as the __init__.py file. Since we now stick to sqlite3, MySQL problems across platforms will be addressed later in a smarter way if we decide to use it.
